### ISSUE TITLE
Manage Gateway API resources

### ISSUE THREAD

**Issue by scotwells** [datum-cloud/cloud-portal#229]
This issue tracks the development of Gateway related views in the cloud portal. We are utilizing the [Gateway API](https://gateway-api.sigs.k8s.io) to provide users with the ability to configure how our L7 proxy forwards traffic to their backend applications. 

The gateway API's openapi spec is currently installed in the staging environment and can be retrieved with the following command: 

```shell
kubectl --context datum-project-scot-dev-833n4x get --raw /apis/resourcemanager.datumapis.com/v1alpha/projects/scot-dev-833n4x/control-plane/openapi/v3 | jq
``` 

The Gateway API we're exposing in our project control plane consists of the following resources:
- Gateway
- HTTPRoute

Each Gateway resource is configured with one or more listeners that can select one or more HTTP Route resources from the control plane. A gateway listener can select HTTP Routes from the same namespace the gateway is in, or any other namespace in the cluster. The gateway status has details on the health of each listener and the routes that have been selected.

The HTTPRoute resources are configured with parent references that point to one or more gateway resources that the HTTPRoute should be attached to. The HTTPRoute then provides a backend ref that configures which backend the Gateway should route traffic to. 

Currently we expect the user to configure an EndpointSlice with the address that should be connected to. 

Here's a full example showing an Endpoint Slice, Gateway, and HTTPRoute that configures a proxy to `example.com`. 

```yaml
---
kind: EndpointSlice
metadata:
  name: test-slice-1
addressType: FQDN
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - example.com
  conditions:
    ready: true
    serving: true
    terminating: false
ports:
- name: http
  appProtocol: http
  port: 80
- name: https
  appProtocol: https
  port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: test-gateway
spec:
  gatewayClassName: datum-external-global-proxy
  listeners:
  - protocol: HTTP
    port: 80
    name: http
    allowedRoutes:
      namespaces:
        from: Same
  - protocol: HTTPS
    port: 443
    name: https
    allowedRoutes:
      namespaces:
        from: Same
    tls:
      mode: Terminate
      options:
        gateway.networking.datumapis.com/certificate-issuer: auto
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-route
spec:
  parentRefs:
  - name: test-gateway
    kind: Gateway
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /plaintext
      backendRefs:
      - group: discovery.k8s.io
        kind: EndpointSlice
        name: test-slice-1
        port: 80
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
            hostname: "example.com"
    - matches:
      - path:
          type: PathPrefix
          value: /tls
      backendRefs:
      - group: discovery.k8s.io
        kind: EndpointSlice
        name: test-slice-1
        port: 443
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
            hostname: "example.com"
```
