### ISSUE TITLE
Create new Endpoint Slice

### ISSUE THREAD

**Issue by scotwells** [datum-cloud/cloud-portal#235]
Support creating a new Endpoint slice using a form. The following sections should be available:

- Metadata
  - Name
  - Labels
  - Annotations
- Address Type - Select box with FQDN as the only option
- Endpoints - One or more endpoints to define
  - Addresses: One or more addresses that should be used for an endpoint
- Ports - One or more ports on the endpoint to make available
  - Name: Unique name given to the port. 
  - App Protocol: The app protocol that's used to connect to the endpoint (e.g. http / https)
  - port: the port on the endpoint to connect to

Here's an example endpoint:

```yaml
kind: EndpointSlice
metadata:
  name: test-slice-1
addressType: FQDN
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - example.com
  conditions:
    ready: true
    serving: true
    terminating: false
ports:
- name: http
  appProtocol: http
  port: 80
- name: https
  appProtocol: https
  port: 443
```
