### ISSUE TITLE
Auto-generate UI

### ISSUE THREAD

**Issue by mustela** [datum-cloud/cloud-portal#375]
We want to explore the idea of auto-generating UI pages based on API specs. For the initial attempt, we’ll use the Network resource, which is already in production. This provides an easy way to compare approaches and evaluate how far we can get.

:warning: **Note**: This is a proof of concept (POC), so let’s keep it as simple as possible.

Here is the [Network API spec](https://gist.github.com/mustela/7ecb609fcb3c98f9b8638626c7eb1ec4).

### Goals

1. Define a minimal configuration structure (class, file, etc.) to specify which resources should be automatically rendered.
A potential configuration for the Network resource could look like:

```yml
resources:
  - name: networks
    api_spec: https://{{datum-host}}/apis/resourcemanager.datumapis.com/v1alpha/projects/{{datum-project}}/control-plane/openapi/v3/apis/networking.datumapis.com/v1alpha?hash=34CB7DDF2C750DB996B2B50822AB7F30C7A03F92E59734FB73878E2C4A37915D6FE8FA8CA7549EF0539BAA464374AE0F89BDEE972D3B4472A9C5FBF4B75AC5C4
    menu:
      label: Networks
      slug: networks # used in the URL - could be different from the name
      parent: connect # this means we will need to keep ids for each menu item
      order: 10 # used to order the menu items
    listing:
      columns: ["name", "IP Family", "IPAM Mode", "MTU", "Created At",]
```
API specs are project-specific, so we can’t cache them globally or fetch them at startup. Instead, we need to fetch them once the project is loaded and cache subsequent calls. We can expire the cache automatically after 1 hour for now.

2. Render a listing page

![Image](https://github.com/user-attachments/assets/87f2c823-def9-4802-9acf-b3faa268db20)

**Note**: Rendering the create/edit and delete forms will be done in a separated issue.

**Comment by gaghan430** [comment]
@mustela for now can we skip the menu part? 
```menu:
      label: Networks
      slug: networks # used in the URL - could be different from the name
      parent: connect # this means we will need to keep ids for each menu item
      order: 10 # used to order the menu items```

this will require major changes to the way we display menus IMO, @yahyafakhroji thoughts?

**Comment by mustela** [comment]
Yeah, totally. I wanted to show a complete config, but I knew that the menu would be a major change. We can definitely skip that part.

**Comment by mustela** [comment]
@gaghan430  Let's omit that for now.

**Comment by gaghan430** [comment]
Josh suggested that instead of relying on the OpenAPI URL, we could use the Group-Version-Kind (GVK) to discover everything from there, so I think the next step would be to fetch info using GVK and generate the columns based on the CRD instead of OpenAPI.
We can also use the additionalPrinterColumns field to construct the columns:

```yaml
versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].reason
      name: Reason
      type: string
```
but to get it, we need access to CRD CMIIW
Is there a way to fetch a CRD from the API based on its GVK?
